export const FETCH_MEME_DATA_SUCCESS = 'FETCH_MEME_DATA_SUCCESS';
export const FETCH_MEME_DATA_FAILED = 'FETCH_MEME_DATA_FAILED';
export const NEXT_MEME = 'NEXT_MEME';
export const PREVIOUS_MEME = 'PREVIOUS_MEME';
export const SET_CURRENT_MEME = 'SET_CURRENT_MEME';
